CREATE TABLE [dbo].[Address]
(
	[Id] INT NOT NULL IDENTITY(1, 1)
,	[CityId] INT NOT NULL
,	[StreetId] INT
,	[PostCode] INT
,	[BuildNr] NVARCHAR(10)
,	[FlatNr] NVARCHAR(10)
,	[CouncilId] INT NOT NULL
,	[LastUpdDt] SMALLDATETIME NOT NULL
,	[LastUpdUs] NVARCHAR(50) NOT NULL
,	CONSTRAINT [PK_Address] PRIMARY KEY CLUSTERED ([Id])
)
