CREATE TABLE [dbo].[Catalog]
(
	[Id] INT NOT NULL IDENTITY(1, 1)
,	[ParentId] INT
,	[Name] NVARCHAR(50) NOT NULL
,	[CouncilId] INT NOT NULL
,	[LastUpdDt] SMALLDATETIME NOT NULL
,	[LastUpdUs] NVARCHAR(50) NOT NULL
,	CONSTRAINT [PK_Catalog] PRIMARY KEY CLUSTERED ([Id])
)
