CREATE TABLE [dbo].[House]
(
	[Id] INT NOT NULL IDENTITY(1, 1)
,	[HouseNr] NVARCHAR(10) NOT NULL
,	[KadastrNr] NVARCHAR(30)
,	[BuildNr] NVARCHAR(10) NOT NULL
,	[AddressId] INT NOT NULL
,	[PhoneNr] NVARCHAR(12)
,	[PhoneCode] NVARCHAR(5)
,	[FaxNr] NVARCHAR(12)
,	[Year] INT
,	[Code] NVARCHAR(50)
,	[CouncilId] INT NOT NULL
,	[LastUpdDt] SMALLDATETIME NOT NULL
,	[LastUpdUs] NVARCHAR(50) NOT NULL
,	CONSTRAINT [PK_House] PRIMARY KEY CLUSTERED ([Id])
)
