CREATE TABLE [dbo].[SYS_Administration]
(
	[Id] INT NOT NULL IDENTITY(1, 1)
,	[Name] NVARCHAR(50) NOT NULL
,	[Description] NVARCHAR(250)
,	[DataBaseName] NVARCHAR(100)
,	[SVVersion] NVARCHAR(50) NOT NULL
,	[DBVersion] NVARCHAR(50) NOT NULL
,	[DataBaseGuid] UNIQUEIDENTIFIER
,	[LastUpdDt] SMALLDATETIME NOT NULL
,	[LastUpdUs] NVARCHAR(50) NOT NULL
,	CONSTRAINT [PK_Administration] PRIMARY KEY CLUSTERED ([Id])
)
